"""hacks table

Revision ID: 6c5b222b6da9
Revises: af3b905617dc
Create Date: 2018-04-19 14:42:34.202374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c5b222b6da9'
down_revision = 'af3b905617dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('place', sa.String(length=128), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hacks_date'), 'hacks', ['date'], unique=False)
    op.create_index(op.f('ix_hacks_name'), 'hacks', ['name'], unique=True)
    op.create_index(op.f('ix_hacks_place'), 'hacks', ['place'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hacks_place'), table_name='hacks')
    op.drop_index(op.f('ix_hacks_name'), table_name='hacks')
    op.drop_index(op.f('ix_hacks_date'), table_name='hacks')
    op.drop_table('hacks')
    # ### end Alembic commands ###
